[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
installCommand = "pnpm install"
buildCommand = "pnpm build:web-only"

[deploy]
staticPublishPath = "dist/web"

[variables]
NODE_ENV = "production"



