[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
installCommand = "npm install"
buildCommand = "npm run build:web-only"

[deploy]
staticPublishPath = "dist/web"

[variables]
NODE_ENV = "production"