[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
installCommand = "pnpm install --no-frozen-lockfile"
buildCommand = "pnpm run build:web-only"

[deploy]
staticPublishPath = "/dist/web"

[variables]
NODE_ENV = "production"


