[build]
builder = "NIXPACKS"

[deploy]
staticPublishPath = "dist/web"

[variables]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://api-interview.csinterviewhelp.com"
VITE_API_TIMEOUT = "10000"
VITE_WEBSOCKET_URL = "wss://api-interview-ws.csinterviewhelp.com"
VITE_YJS_WEBSOCKET_URL = "wss://api-interview-ws.csinterviewhelp.com"
VITE_APP_NAME = "Interview Collaboration System"
VITE_APP_VERSION = "1.0.0"
VITE_APP_DEFAULT_LANGUAGE = "zh-CN"
VITE_ENABLE_REGISTRATION = "false"
VITE_ENABLE_ROOM_PASSWORD = "true"
VITE_MAX_ROOM_MEMBERS = "10"
VITE_AUTO_SAVE_INTERVAL = "3000"
VITE_PROD = "true"
